# A16 / RULE 4.2a: banned recognition literals must not appear in refit_lawband.cpp
get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_src "${_root}/src/refit_lawband.cpp")
if(NOT EXISTS "${_src}")
    message(FATAL_ERROR "missing ${_src}")
endif()
file(READ "${_src}" _txt)
if(_txt MATCHES "0\\.0125")
    message(FATAL_ERROR "RULE 4.2a: 0.0125 appears in refit_lawband.cpp")
endif()
if(_txt MATCHES "0\\.261799")
    message(FATAL_ERROR "RULE 4.2a: 0.261799 appears in refit_lawband.cpp")
endif()
# SPEC A16: 15. / 15.0 as a token (not 1e-15, 1.5, 150)
string(REGEX MATCH "(^|[^0-9.])15\\.0?([^0-9]|$)" _m15 "${_txt}")
if(_m15)
    message(FATAL_ERROR "RULE 4.2a: 15 / 15.0 appears as a threshold in refit_lawband.cpp")
endif()
message(STATUS "RULE 4.2a grep: clean")
