# A15: banned prismaticity literals must not appear in src/refit_prism.{cpp,hpp}
get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
foreach(_f IN ITEMS src/refit_prism.cpp src/refit_prism.hpp)
    set(_src "${_root}/${_f}")
    if(NOT EXISTS "${_src}")
        message(FATAL_ERROR "missing ${_src}")
    endif()
    file(READ "${_src}" _txt)
    if(_txt MATCHES "0\\.0125")
        message(FATAL_ERROR "A15: 0.0125 appears in ${_f}")
    endif()
    if(_txt MATCHES "8\\.375")
        message(FATAL_ERROR "A15: 8.375 appears in ${_f}")
    endif()
    if(_txt MATCHES "2\\.825")
        message(FATAL_ERROR "A15: 2.825 appears in ${_f}")
    endif()
    if(_txt MATCHES "11\\.2")
        message(FATAL_ERROR "A15: 11.2 appears in ${_f}")
    endif()
    if(_txt MATCHES "288\\.82")
        message(FATAL_ERROR "A15: 288.82 appears in ${_f}")
    endif()
    if(_txt MATCHES "280\\.45")
        message(FATAL_ERROR "A15: 280.45 appears in ${_f}")
    endif()
    if(_txt MATCHES "277\\.62")
        message(FATAL_ERROR "A15: 277.62 appears in ${_f}")
    endif()
    if(_txt MATCHES "0\\.261799")
        message(FATAL_ERROR "A15: 0.261799 appears in ${_f}")
    endif()
    string(REGEX MATCH "(^|[^0-9.])15\\.0?([^0-9]|$)" _m15 "${_txt}")
    if(_m15)
        message(FATAL_ERROR "A15: 15 / 15.0 appears as a threshold in ${_f}")
    endif()
endforeach()
message(STATUS "A15 prism literal ban: clean")
